theme: jekyll-theme-minimal
title: Vincenzo Arceri
description: Vincenzo Arceri's home site
logo: photo_small.jpg

mail-work: vincenzo.arceri@univr.com
linkedin: https://www.linkedin.com/in/vincenzo-arceri-923b7582/
scholar: https://scholar.google.com/citations?user=jhTPNVEAAAAJ&hl=en
research-gate: https://www.researchgate.net/profile/Vincenzo_Arceri
facebook: https://www.facebook.com/vincenzo.arceri/
instagram: https://www.instagram.com/vincenzo_arceri/